apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: mtgpupods.lsalab.nthu
spec:
    group: lsalab.nthu
    version: v1
    scope: Namespaced
    names:
        plural: mtgpupods
        singular: mtgpupod
        kind: MtgpuPod
        shortNames:
        - mtgp
