/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	mtgpupodv1 "lsalab.nthu/mtgpu/pkg/apis/mtgpupod/v1"
)

// FakeMtgpuPods implements MtgpuPodInterface
type FakeMtgpuPods struct {
	Fake *FakeLsalabV1
	ns   string
}

var mtgpupodsResource = schema.GroupVersionResource{Group: "lsalab.nthu/mtgpu", Version: "v1", Resource: "mtgpupods"}

var mtgpupodsKind = schema.GroupVersionKind{Group: "lsalab.nthu/mtgpu", Version: "v1", Kind: "MtgpuPod"}

// Get takes name of the mtgpuPod, and returns the corresponding mtgpuPod object, and an error if there is any.
func (c *FakeMtgpuPods) Get(name string, options v1.GetOptions) (result *mtgpupodv1.MtgpuPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mtgpupodsResource, c.ns, name), &mtgpupodv1.MtgpuPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mtgpupodv1.MtgpuPod), err
}

// List takes label and field selectors, and returns the list of MtgpuPods that match those selectors.
func (c *FakeMtgpuPods) List(opts v1.ListOptions) (result *mtgpupodv1.MtgpuPodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mtgpupodsResource, mtgpupodsKind, c.ns, opts), &mtgpupodv1.MtgpuPodList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &mtgpupodv1.MtgpuPodList{ListMeta: obj.(*mtgpupodv1.MtgpuPodList).ListMeta}
	for _, item := range obj.(*mtgpupodv1.MtgpuPodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mtgpuPods.
func (c *FakeMtgpuPods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mtgpupodsResource, c.ns, opts))

}

// Create takes the representation of a mtgpuPod and creates it.  Returns the server's representation of the mtgpuPod, and an error, if there is any.
func (c *FakeMtgpuPods) Create(mtgpuPod *mtgpupodv1.MtgpuPod) (result *mtgpupodv1.MtgpuPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mtgpupodsResource, c.ns, mtgpuPod), &mtgpupodv1.MtgpuPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mtgpupodv1.MtgpuPod), err
}

// Update takes the representation of a mtgpuPod and updates it. Returns the server's representation of the mtgpuPod, and an error, if there is any.
func (c *FakeMtgpuPods) Update(mtgpuPod *mtgpupodv1.MtgpuPod) (result *mtgpupodv1.MtgpuPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mtgpupodsResource, c.ns, mtgpuPod), &mtgpupodv1.MtgpuPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mtgpupodv1.MtgpuPod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMtgpuPods) UpdateStatus(mtgpuPod *mtgpupodv1.MtgpuPod) (*mtgpupodv1.MtgpuPod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mtgpupodsResource, "status", c.ns, mtgpuPod), &mtgpupodv1.MtgpuPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mtgpupodv1.MtgpuPod), err
}

// Delete takes name of the mtgpuPod and deletes it. Returns an error if one occurs.
func (c *FakeMtgpuPods) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mtgpupodsResource, c.ns, name), &mtgpupodv1.MtgpuPod{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMtgpuPods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mtgpupodsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &mtgpupodv1.MtgpuPodList{})
	return err
}

// Patch applies the patch and returns the patched mtgpuPod.
func (c *FakeMtgpuPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *mtgpupodv1.MtgpuPod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mtgpupodsResource, c.ns, name, pt, data, subresources...), &mtgpupodv1.MtgpuPod{})

	if obj == nil {
		return nil, err
	}
	return obj.(*mtgpupodv1.MtgpuPod), err
}
