/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "lsalab.nthu/mtgpu/pkg/apis/mtgpupod/v1"
	scheme "lsalab.nthu/mtgpu/pkg/client/clientset/versioned/scheme"
)

// MtgpuPodsGetter has a method to return a MtgpuPodInterface.
// A group's client should implement this interface.
type MtgpuPodsGetter interface {
	MtgpuPods(namespace string) MtgpuPodInterface
}

// MtgpuPodInterface has methods to work with MtgpuPod resources.
type MtgpuPodInterface interface {
	Create(*v1.MtgpuPod) (*v1.MtgpuPod, error)
	Update(*v1.MtgpuPod) (*v1.MtgpuPod, error)
	UpdateStatus(*v1.MtgpuPod) (*v1.MtgpuPod, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.MtgpuPod, error)
	List(opts metav1.ListOptions) (*v1.MtgpuPodList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MtgpuPod, err error)
	MtgpuPodExpansion
}

// mtgpuPods implements MtgpuPodInterface
type mtgpuPods struct {
	client rest.Interface
	ns     string
}

// newMtgpuPods returns a MtgpuPods
func newMtgpuPods(c *LsalabV1Client, namespace string) *mtgpuPods {
	return &mtgpuPods{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mtgpuPod, and returns the corresponding mtgpuPod object, and an error if there is any.
func (c *mtgpuPods) Get(name string, options metav1.GetOptions) (result *v1.MtgpuPod, err error) {
	result = &v1.MtgpuPod{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mtgpupods").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MtgpuPods that match those selectors.
func (c *mtgpuPods) List(opts metav1.ListOptions) (result *v1.MtgpuPodList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.MtgpuPodList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mtgpupods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mtgpuPods.
func (c *mtgpuPods) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mtgpupods").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a mtgpuPod and creates it.  Returns the server's representation of the mtgpuPod, and an error, if there is any.
func (c *mtgpuPods) Create(mtgpuPod *v1.MtgpuPod) (result *v1.MtgpuPod, err error) {
	result = &v1.MtgpuPod{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mtgpupods").
		Body(mtgpuPod).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mtgpuPod and updates it. Returns the server's representation of the mtgpuPod, and an error, if there is any.
func (c *mtgpuPods) Update(mtgpuPod *v1.MtgpuPod) (result *v1.MtgpuPod, err error) {
	result = &v1.MtgpuPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mtgpupods").
		Name(mtgpuPod.Name).
		Body(mtgpuPod).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mtgpuPods) UpdateStatus(mtgpuPod *v1.MtgpuPod) (result *v1.MtgpuPod, err error) {
	result = &v1.MtgpuPod{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mtgpupods").
		Name(mtgpuPod.Name).
		SubResource("status").
		Body(mtgpuPod).
		Do().
		Into(result)
	return
}

// Delete takes name of the mtgpuPod and deletes it. Returns an error if one occurs.
func (c *mtgpuPods) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mtgpupods").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mtgpuPods) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mtgpupods").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mtgpuPod.
func (c *mtgpuPods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.MtgpuPod, err error) {
	result = &v1.MtgpuPod{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mtgpupods").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
